source 'https://github.com/CocoaPods/Specs.git'

target 'DTVTableView', :exclusive => true do
  pod "DTVTableView", :path => "../"
end

#target 'Tests', :exclusive => true do
#  pod "DTVTableView", :path => "../"
#
#
#end
