source 'https://github.com/CocoaPods/Specs.git'

target 'DTVTableViewExample', :exclusive => true do
  pod "DTVTableView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DTVTableView", :path => "../"
end
