language: objective-c
before_install:
  - bundle install
  - cd Example && bundle exec pod install && cd -
cache:
  bundler: true
  directories: Example/Pods
script:
  - bundle exec pod lib testing
after_success:
  - bundle exec slather coverage -t
